os:
  - linux
language: nix
nix: 2.3.6
sudo: required
git:
  depth: 1
  submodules: false
before_script:
  - sudo mkdir -p /etc/nix
  - echo "trusted-users = root $USER" | sudo tee -a /etc/nix/nix.conf
script:
  - |
    nix-env -iA shellcheck -f '<nixpkgs>'
    # for some reason, `find` with multiple search paths piped to xargs
    # produces no output
    find lib -type f -print | xargs shellcheck -x
    find {lib,libexec,bin} -type f -print | xargs shellcheck -x
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - echo "trusted-users = root travis" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon
  - cachix use maker
  - cachix push maker --watch-store &
  - nix-build -j2 | cachix push maker
